### ISSUE TITLE
compile error...

### ISSUE THREAD

**Issue by jstrachan** [TiarkRompf/replhtml#1]
Interesting sounding project! 
I just tried it but got this...

[info] Running ch.epfl.lamp.replhtml.ReplMain 
2010-10-07 14:46:30.141:INFO::Logging to StdErrLog::DEBUG=false via org.eclipse.jetty.util.log.StdErrLog
/workspace/java/replhtml/project/boot/scala-2.8.0/lib/scala-library.jar:/workspace/java/replhtml/project/boot/scala-2.8.0/lib/scala-compiler.jar:
EXTRA:null
<script>:3: error: value replhtml is not a member of package ch.epfl.lamp
  var value: ch.epfl.lamp.replhtml.ReplServlet = _
                          ^
<script>:4: error: value replhtml is not a member of package ch.epfl.lamp
  def set(x: Any) = value = x.asInstanceOf[ch.epfl.lamp.replhtml.ReplServlet]
                                                        ^
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:185)
        at scala.None$.get(Option.scala:183)
        at scala.tools.nsc.Interpreter.bind(Interpreter.scala:622)
        at ch.epfl.lamp.replhtml.ReplServlet$$anon$2.unleash(ReplServlet.scala:28)

**Comment by TiarkRompf** [comment]
interesting, here it works fine. the line before EXTRA is the classpath, this should contains all the jetty jars and the target jars as well -- I wonder why it doesn't. probably something is wrong with the dependencies in the sbt script.

**Comment by TiarkRompf** [comment]
apparently it happens if you do `sbt update run` on a fresh checkout. if you use `sbt update`, then `sbt compile` and then `sbt run` it works.

**Comment by jstrachan** [comment]
Aha! Yeah, I tend to fire up sbt in a shell then do "update" or "run" separately. 

Thanks for figuring that out - and I've no idea why there's a difference in behaviour in sbt :)

**Comment by TiarkRompf** [comment]
I use a custom system property to set the repl classpath, and that property is initialized with sbt's compile classpath. maybe the initialization happens too early somehow.

**Comment by TiarkRompf** [comment]
should be fixed now
