### ISSUE TITLE
on OS X Java 6 Chrome browser I get this error when trying to evaluate code...

### ISSUE THREAD

**Issue by jstrachan** [TiarkRompf/replhtml#3]
> > > embedded jetty server started. press any key to stop.
> > > 2010-10-07 16:21:29.341:WARN::handle failed
> > > java.lang.IllegalArgumentException: !utf8
> > >         at org.eclipse.jetty.util.Utf8StringBuilder.append(Utf8StringBuilder.java:119)
> > >         at org.eclipse.jetty.websocket.WebSocketParser.parseNext(WebSocketParser.java:147)
> > >         at org.eclipse.jetty.websocket.WebSocketConnection.handle(WebSocketConnection.java:96)
> > >         at org.eclipse.jetty.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:474)
> > >         at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:437)
> > >         at java.lang.Thread.run(Thread.java:637)

**Comment by TiarkRompf** [comment]
http://blog.chromium.org/2010/06/websocket-protocol-updated.html

**Comment by TiarkRompf** [comment]
updating to jetty 7.1.6 did the trick.
